export const SERVER_LINK: string = '/api/kir3kin/'
export const DEFAULT_CARD_THUMB: string = 'http://via.placeholder.com/250x200'
export const DEFAULT_PROJECT_IMG: string = 'http://via.placeholder.com/600x370'
export const PROJECT_IMAGE_FOLDER: string = '../assets/images/projects/'
export const PROJECT_IMAGE_EXTENTION: string = '.jpg'
export const HOME_LINK = '/'
export const storageName = 'FilterData'
